apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-depname
  namespace: placeholder-namespace
  ownerReferences:
    - apiVersion: theia.cloud/v1beta9
      kind: AppDefinition
      name: placeholder
      uid: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder-app
  template:
    metadata:
      labels:
        app: placeholder-app
    spec:
      automountServiceAccountToken: false
      # initContainers:
      # - name: wondershaper-init
      #   image: gcr.io/kubernetes-238012/theia-cloud-wondershaper
      #   securityContext:
      #     capabilities:
      #       add:
      #       - NET_ADMIN
      containers:
        - name: placeholder-definitionname
          image: placeholder-image
          imagePullPolicy: placeholder-pull-policy
          ports:
            - containerPort: placeholder-port
              name: application
            placeholder-monitor-port
          resources:
            limits:
              cpu: placeholder-cpu-limits
              memory: placeholder-memory-limits
            requests:
              cpu: placeholder-cpu-requests
              memory: placeholder-memory-requests
          env:
          - name: THEIACLOUD_SERVICE_AUTH_TOKEN
            value: placeholder-env-service-auth-token
          - name: THEIACLOUD_APP_ID
            value: placeholder-env-app-id
          - name: THEIACLOUD_SERVICE_URL
            value: placeholder-env-service-url
          - name: THEIACLOUD_SESSION_UID
            value: placeholder-env-session-uid
          - name: THEIACLOUD_SESSION_NAME
            value: placeholder-env-session-name
          - name: THEIACLOUD_SESSION_USER
            value: placeholder-env-session-user
          - name: THEIACLOUD_SESSION_URL
            value: placeholder-env-session-url
          - name: THEIACLOUD_SESSION_SECRET
            value: placeholder-env-session-secret
          - name: THEIACLOUD_MONITOR_ENABLE_ACTIVITY_TRACKER
            value: placeholder-enable-activity-tracker
          - name: THEIACLOUD_MONITOR_PORT
            value: placeholder-monitor-env-port
          - name: THEIACLOUD_KEYCLOAK_URL
            value: placeholder-keycloak-env-url
          - name: THEIACLOUD_KEYCLOAK_REALM
            value: placeholder-keycloak-env-realm
          - name: THEIACLOUD_KEYCLOAK_CLIENT_ID
            value: placeholder-keycloak-env-clientid
          securityContext:
            runAsUser: placeholder-uid
            runAsGroup: placeholder-uid
      securityContext:
        fsGroup: placeholder-uid
