apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-depname
  namespace: placeholder-namespace
  ownerReferences:
    - apiVersion: theia.cloud/v2beta
      kind: AppDefinition
      name: placeholder
      uid: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder-app
  template:
    metadata:
      labels:
        app: placeholder-app
    spec:
      automountServiceAccountToken: false
      # initContainers:
      # - name: wondershaper-init
      #   image: gcr.io/kubernetes-238012/theia-cloud-wondershaper
      #   securityContext:
      #     capabilities:
      #       add:
      #       - NET_ADMIN
      containers:
        - name: placeholder-definitionname
          image: placeholder-image
          ports:
            - containerPort: placeholder-port
          resources:
            limits:
              cpu: placeholder-cpu-limits
              memory: placeholder-memory-limits
            requests:
              cpu: placeholder-cpu-requests
              memory: placeholder-memory-requests
          env:
          - name: THEIA_CLOUD_APP_ID
            value: placeholder-env-app-id
          - name: THEIA_CLOUD_SERVICE_URL
            value: placeholder-env-service-url
          - name: THEIA_CLOUD_SESSION_UID
            value: placeholder-env-session-uid
          - name: THEIA_CLOUD_SESSION_NAME
            value: placeholder-env-session-name
          - name: THEIA_CLOUD_SESSION_USER
            value: placeholder-env-session-user
          - name: THEIA_CLOUD_SESSION_URL
            value: placeholder-env-service-url
