apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ tpl (.Values.ingress.instanceName | toString) . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if not .Values.hosts.usePaths }}
    cert-manager.io/cluster-issuer: {{ tpl (.Values.ingress.clusterIssuer | toString) . }}
    {{ if .Values.ingress.theiaCloudCommonName }}cert-manager.io/common-name: "Theia.Cloud" {{ end }}
    acme.cert-manager.io/http01-ingress-class: nginx
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # rewrite: Rewrite all URLs not ending with a segment containing . or ? with a trailing slash
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header 'X-Forwarded-Uri' $request_uri;
      rewrite ^([^.?]*[^/])$ $1/ redirect;
spec:
  tls:
  - hosts:
  {{- if .Values.hosts.usePaths }}
    - {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
  {{- else }}
    - {{ tpl (.Values.hosts.instance | toString) . }}
    secretName: ws-cert-secret
  {{- end }}
  rules:
    {{- if .Values.hosts.usePaths }}
    - host: {{ tpl (.Values.hosts.paths.baseHost | toString) . }}
    {{- else }}
    - host: {{ tpl (.Values.hosts.instance | toString) . }}
    {{- end }}
      http:
      