apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-deployment
  labels:
    app: landing-page
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      automountServiceAccountToken: false
      containers:
        - name: landing-page-container
          image: {{ tpl (.Values.landingPage.image | toString) . }}
          imagePullPolicy: {{ if .Values.landingPage.imagePullPolicy }}{{ tpl (.Values.landingPage.imagePullPolicy | toString) . }}{{ else }}{{ tpl (.Values.imagePullPolicy | toString) . }}{{ end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /config.js
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: landing-page-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
            - name: landing-page-config
              mountPath: /usr/share/nginx/html/logo.svg
              subPath: logo.svg
      {{- if .Values.landingPage.imagePullSecret }}
      imagePullSecrets:
        - name: {{ tpl (.Values.landingPage.imagePullSecret | toString) . }}
      {{- end }}
      volumes:
        - name: landing-page-config
          configMap:
            name: landing-page-config
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page-service
  labels:
    app: landing-page
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: landing-page
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
