apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-api-access
  namespace: {{ .Release.Namespace }}
rules:
  -
    apiGroups:
      - ""
      - apiextensions.k8s.io
      - theia.cloud
      - networking.k8s.io
      - apps
    resources:
      - customresourcedefinitions
      - templates
      - ingresses
      - workspaces
      - persistentvolumes
      - persistentvolumeclaims
      - services
      - configmaps
      - deployments
    verbs: ["list", "create", "watch", "get", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-api-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-api-access
subjects:
- kind: ServiceAccount
  name: operator-api-service-account
  namespace: {{ .Release.Namespace }}