apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-api-access
  namespace: {{ .Release.Namespace }}
rules:
  -
    apiGroups:
      - ""
      - theia.cloud
    resources:
      - appdefinitions
      - sessions
      - workspaces
    verbs: ["list", "create", "watch", "get", "patch", "delete"]
  -
    apiGroups:
      - ""
      - metrics.k8s.io
    resources:
      - pods
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-api-access
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-api-access
subjects:
- kind: ServiceAccount
  name: service-api-service-account
  namespace: {{ .Release.Namespace }}