apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      # we need to be able to create and read sessions
      automountServiceAccountToken: true
      serviceAccountName: service-api-service-account
      containers:
      - name: service-container
        image: {{ .Values.service.image }}
        ports:
        - name: http
          containerPort: {{ .Values.hosts.servicePort }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: service-config
      {{- if .Values.service.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.service.imagePullSecret }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: service-service
  labels:
    app: service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.hosts.servicePort }}
      targetPort: {{ .Values.hosts.servicePort }}