imagePullPolicy: Always

app:
  id: asdfghjkl
  name: Theia Blueprint

issuer:
  email: jfaltermeier@eclipsesource.com

image:
  name: theiacloud/theia-cloud-demo:0.8.0.MS8
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "30"
  imagePullPolicy: IfNotPresent

hosts:
  usePaths: false
  service: service.theia-cloud.io
  serviceProtocol: https
  landing: try.theia-cloud.io
  instance: ws.theia-cloud.io

landingPage:
  image: theiacloud/theia-cloud-try-now-page:0.8.0.MS8
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: true
  additionalApps:
    coffee-editor:
      label: "Coffee Editor"
    cdt-cloud-demo:
      label: "CDT.cloud Blueprint"

keycloak:
  enable: false
  authUrl: ""
  realm: ""
  clientId: ""
  clientSecret: ""
  cookieSecret: ""

operator:
  eagerStart: false
  cloudProvider: "GKE"
  bandwidthLimiter: "WONDERSHAPER"
  sessionsPerUser: "1"

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false

monitor:
  enable: false
  activityTracker:
    enable: true
    interval: 1
