app:
  id: asdfghjkl
  name: CDT.cloud Blueprint
  logo: cdtcloud.png

issuer:
  email: mmorlock@example.com

image:
  name: theiacloud/cdt-blueprint
  pullSecret: ""

hosts:
  service: service.192.168.39.173.nip.io
  landing: theia.cloud.192.168.39.173.nip.io
  instance: ws.192.168.39.173.nip.io

landingPage:
  image: theiacloud/theia-cloud-landing-page
  appDefinition: "theia-cloud-demo"

keycloak:
  enable: false
  authUrl: "https://keycloak.url/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "RZdfb7bbhy26C6EObmvlHiZcZhar34O0"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  image: theiacloud/theia-cloud-operator
  eagerStart: false
  ephemeralStorage: true
  cloudProvider: "K8S"
  bandwidthLimiter: "K8SANNOTATION"
  killAfter: "FIXEDTIME"

service:
  image: theiacloud/theia-cloud-service

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false
