app:
  id: asdfghjkl
  name: Theia Blueprint
  logo: theiablueprint.png

issuer:
  email: jfaltermeier@eclipsesource.com

image:
  name: theiacloud/theia-cloud-demo:0.8.0.MS7
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "30"

hosts:
  service: service.34.141.62.32.nip.io
  serviceProtocol: https
  landing: theia.cloud.34.141.62.32.nip.io
  instance: ws.34.141.62.32.nip.io

landingPage:
  image: theiacloud/theia-cloud-try-now-page:0.8.0.MS7
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: true

keycloak:
  enable: false
  authUrl: ""
  realm: ""
  clientId: ""
  clientSecret: ""
  cookieSecret: ""

operator:
  image: theiacloud/theia-cloud-operator:0.8.0.MS7
  eagerStart: false
  cloudProvider: "GKE"
  bandwidthLimiter: "WONDERSHAPER"
  sessionsPerUser: "1"

service:
  image: theiacloud/theia-cloud-service:0.8.0.MS7

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: letsencrypt-prod
  theiaCloudCommonName: false
