app:
  name: Try Now Page Test Application
  # logo: test.svg use full path; not working yet after helm-repository switch

image:
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "3"
  imagePullPolicy: IfNotPresent

hosts:
  usePaths: false
  service: service.192.168.39.3.nip.io
  serviceProtocol: https
  landing: theia.cloud.192.168.39.3.nip.io
  instance: ws.192.168.39.3.nip.io

landingPage:
  image: theiacloud/theia-cloud-try-now-page:0.8.1.MS3
  imagePullPolicy: Always
  appDefinition: "theia-cloud-demo"
  ephemeralStorage: true
  additionalApps:
    cdt-cloud-demo:
      label: "CDT.cloud Blueprint"

keycloak:
  enable: false

operator:
  cloudProvider: MINIKUBE
  imagePullPolicy: Always

service:
  imagePullPolicy: Always

ingress:
  clusterIssuer: theia-cloud-selfsigned-issuer
  theiaCloudCommonName: true

monitor:
  enable: false
  