app:
  id: asdfghjkl
  name: CDT.cloud Blueprint
  logo: cdtcloud.png

issuer:
  email: mmorlock@example.com

image:
  name: theiacloud/cdt-blueprint
  pullSecret: ""
  timeoutStrategy: "FIXEDTIME"
  timeoutLimit: "30"

hosts:
  service: service.192.168.39.3.nip.io
  serviceProtocol: https
  landing: theia.cloud.192.168.39.3.nip.io
  instance: ws.192.168.39.3.nip.io

landingPage:
  image: theiacloud/theia-cloud-landing-page:0.8.0.MS7
  appDefinition: "theia-cloud-demo"

keycloak:
  enable: false
  authUrl: "https://keycloak.192.168.39.3.nip.io/auth/"
  realm: "TheiaCloud"
  clientId: "theia-cloud"
  clientSecret: "zpF6PUpM3RmfVecInloasXTjn1yc88Dp"
  cookieSecret: "OQINaROshtE9TcZkNAm5Zs2Pv3xaWytBmc5W7sPX7ws="

operator:
  image: theiacloud/theia-cloud-operator:0.8.0.MS7
  eagerStart: false
  ephemeralStorage: true
  cloudProvider: "K8S"
  bandwidthLimiter: "K8SANNOTATION"
  sessionsPerUser: "1"

service:
  image: theiacloud/theia-cloud-service:0.8.0.MS7

ingress:
  instanceName: "theia-cloud-demo-ws-ingress"
  clusterIssuer: theia-cloud-selfsigned-issuer
  theiaCloudCommonName: true
