apiVersion: theia.cloud/v7beta
kind: AppDefinition
metadata:
  name: coffee-editor
  namespace: theiacloud
spec:
  downlinkLimit: 30000
  image: eu.gcr.io/kubernetes-238012/coffee-editor:v0.7.17
  imagePullPolicy: IfNotPresent
  ingressname: theia-cloud-demo-ws-ingress
  limitsCpu: "2"
  limitsMemory: 2400M
  maxInstances: 4
  minInstances: 0
  id: coffee-editor
  port: 3000
  requestsCpu: 100m
  requestsMemory: 1000M
  timeout:
    limit: 30
    strategy: FIXEDTIME
  uid: 1001
  uplinkLimit: 30000
  mountPath: /home/project/persisted
  monitor:
    port: 8081
    activityTracker:
      timeoutAfter: 30
      notifyAfter: 25