apiVersion: theia.cloud/v8beta
kind: AppDefinition
metadata:
  name: theia-cloud-demo
  namespace: theiacloud
spec:
  downlinkLimit: 30000
  image: theiacloud/theia-cloud-demo:0.8.1.OSWeek23-v4
  imagePullPolicy: IfNotPresent
  ingressname: theia-cloud-demo-ws-ingress
  limitsCpu: "2"
  limitsMemory: 1200M
  maxInstances: 10
  minInstances: 0
  name: theia-cloud-demo
  port: 3000
  requestsCpu: 100m
  requestsMemory: 1000M
  timeout:
    limit: 30
    strategy: FIXEDTIME
  uid: 101
  uplinkLimit: 30000
  mountPath: /home/project/persisted
  monitor:
    port: 8081
    activityTracker:
      timeoutAfter: 30
      notifyAfter: 25