fullnameOverride: "keycloak"
httpRelativePath: "/keycloak/"

auth:
  adminUser: admin

image:
  # Configure using repository bitnamilegacy because bitnami has removed the bitnami repository in favor of a paid service
  repository: bitnamilegacy/keycloak

postgresql:
  # Configure using repository bitnamilegacy because bitnami has removed the bitnami repository in favor of a paid service
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  metrics:
    image:
      repository: bitnamilegacy/bitnami-exporter

ingress:
  enabled: true
  ingressClassName: "nginx"
  path: "/keycloak/"
  pathType: "ImplementationSpecific"
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    acme.cert-manager.io/http01-ingress-path-type: "ImplementationSpecific"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "128k"
    cert-manager.io/cluster-issuer: ${cluster-issuer}
    cert-manager.io/common-name: ${common-name}
  tls: true
