fullnameOverride: "keycloak"
httpRelativePath: "/keycloak/"

auth:
  adminUser: admin

ingress:
  enabled: true
  ingressClassName: "nginx"
  path: "/keycloak/"
  annotations: 
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    cert-manager.io/cluster-issuer: ${cluster-issuer}
    cert-manager.io/common-name: "Keycloak"
  tls: true