name: Landing Page CI

on:
  push:
    branches:
      - main
    paths:
      - "node/common/**"
      - "node/landing-page/**"
      - "dockerfiles/landing-page/**"
      # Publish when a workflow has changed (this is needed to detect version updates)
      - ".github/workflows/ci-landing-page.yml"
      - ".github/workflows/reusable-docker.yml"
  pull_request:
    branches:
      - main
    paths:
      - "node/common/**"
      - "node/landing-page/**"
      - "dockerfiles/landing-page/**"
  release:
    types:
      - published

jobs:
  call-reusable-docker-workflow:
    uses: ./.github/workflows/reusable-docker.yml
    with:
      docker_org: theiacloud
      docker_image: theia-cloud-landing-page
      docker_file: dockerfiles/landing-page/Dockerfile
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
