name: Common node package CI

on:
  push:
    branches:
      - main
    paths:
      - "node/common/**"
      # Publish when a workflow has changed (this is needed to detect version updates)
      - ".github/workflows/ci-node-common.yml"
      - ".github/workflows/reuseable-npm.yml"
  pull_request:
    branches:
      - main
    paths:
      - "node/common/**"
  release:
    types:
      - published

jobs:
  call-reusable-npm-workflow:
    uses: ./.github/workflows/reusable-npm.yml
    with:
      package_workspace: common
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
