name: "[THEIA] 3PP License Check"

on:
  push:
    branches:
      - main
    paths:
      - "theia/**"
      - ".github/workflows/eclipse-npm-license-check-theia.yml"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "theia/**"
      - ".github/workflows/eclipse-npm-license-check-theia.yml"

jobs:
  License-check:
    name: 3PP License Check using dash-licenses

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [20]
        java: [11]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    defaults:
      run:
        working-directory: ./theia

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Use Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java }}

      - name: Run theia dash-licenses
        shell: bash
        run: |
          sudo apt-get install libsecret-1-dev
          yarn --frozen-lockfile --ignore-scripts
          yarn license:check
        env:
          DASH_TOKEN: ${{ secrets.DASH_LICENSES_PAT }}
